export default {
  sshStatus: {
    systemInfo: "System Info",
    cpuInfo: "CPU Info",
    cpuName: "Name",
    cpuClock: "Clock",
    cpuCoreCount: "Logic Core Count",
    hostname: "Host Name",
    os: "OS",
    arch: "Architecture",
    runTime: "Run Time",
    kernelVersion: "Kernel Version",
    systemStatus: "System Status",
    memory: "Memory",
    disk: "Disk",
    network: "Network",
  },
  common: {
    choose: "Choose"
  },
  global: {
    "changeLog": "Changes",
    "document": "Document",
    "console": "Console",
    "plan": "Plan",
    "login": "Login",
    "logout": "Log out",
  },
  connect: {
    dm: "DM8",
    title: "Connect to server",
    name: "Name",
    group: "Group",
    readOnly: "Read Only",
    scope: "Connection Scope",
    success: "Success!",
    error: "Connection error!",
    global: "Global",
    current: "Current Workspace",
    connecting: "Connect",
    save: "Save",
    close: "Close",
    sshTunnel: "SSH Tunnel",
    connectTimeout: "Connect Timeout",
    requestTimeout: "Request Timeout",
    useSSL: "Use SSL",
    hideSystemSchema: "Hide System Schema",
    usingConnectString: "Use Connection String",
    chooseSqlite: "Choose Database File",
    advance: "Advance Option",
  },
  config: {
    safeUpdateMode: "Safe Update Mode",
    serverType: "Server Type",
    host: "Host",
    port: "Port",
    username: "Username",
    password: "Password",
    database: "Database",
    dialect: "Dialect",
    driverName: "Driver Name",
    driverPath: "Driver Path",
    showedDatabases: "Showed Databases",
    timeZone: "Time Zone",
    groupingTables:"Grouping Tables",
    groupingThreshold:"Grouping Threshold",
    trimCountSQL:"Trim Count SQL",
    showForeignKey:"Show Foreign Key",
  },
  offline: {
    online:"Just Log in with your premium account, no machine limit.",
    detail: "Get the machine Id and send it to support@database-client.com, we will generate an license and reply, each account can get up to 3 offline license.",
    getMachineId: "Get Machine Id",
    activate: "Activate",
  },
  result: {
    export: "Export",
    exportOption: "Export Option",
    importExternal: "Import External Data",
    exportType: "Export Type",
    removeLimit: "Remove Pagination SQL",
    cancel: "Cancel",
    insert: "Insert",
    update: "Update",
    confirm: "Confirm",
    searchNotice: "Input To Search Data",
    deleteNotice: "You need to select at least one row of data!",
    deleteClickHouseNotice: "ClickHouse don't not support delete!",
    cost: "Cost",
    copy: "Copy",
    editDialog: "Edit Row",
    copyDialog: "Copy Row",
  },
  pay: {
    connectNotice: "<span style='color:var(--vscode-terminal-ansiRed)'>Note</span>: This extension needs to be paid to unlock all features, if you are against paid software, please uninstall it immediately, so that we can keep the good mood!",
    notice: "This project is no longer maintain for free and requires payment to unlock all features.",
    notice2: "At the same time I will put more effort into developing this project.",
    freePlanInstalled: "Installed",
    buyPlan: "Buy Now",
  },
  toolbar: {
    reportIssue: "Report issue",
    clearCache: "Clear Cache",
    payAdvice: "Premium account will remove this badge",
  },
  console: {
    configuration: "Connection Configuration",
    resetConfig: "Reset",
    edit: "Edit",
    export: "Export",
    import: "Import",
    sync: "Cloud Sync",
    mergeConfirm: "There is already created connection, select the action you want to perform",
    merge: "Merge",
    overwrite: "Overwrite",
    upload: "Upload",
    download: "Download",
  },
  plan: {
    activation:"Activation",
    perYear: "Per Year",
    installed: "Installed",
    free: "Free",
    about: "About Project",
    document: "Document",
    freeTier: "Free Tier",
    buyNow: "Buy Now",
    basicNotice: "Will not collect your any information and no ads.",
    basicSQLCompletion: "SQL Completion",
    basicDesc: "A simple way to get started with Database Client",
    premiumDesc: "For engineers looking to boost productivity",
    allFeature: "All Basic Features",
    otherFeature: "SFTP Saver, SQL History Support",
    freeLimitConnection: "Limited of 3 connections",
    unlimitConnection: "Unlimited Connections",
    cloudSync: "Cloud Config Sync",
    workLevelConnection: "Workspace Level Connection",
    intelliSenseSQLCompletion: "More IntelliSense SQL Completion",
  }
}