export default {
  sshStatus: {
    systemInfo: "系统信息",
    cpuInfo: "CPU信息",
    cpuName: "名称",
    cpuClock: "频率",
    cpuCoreCount: "逻辑核心数",
    hostname: "主机名",
    os: "操作系统",
    arch: "架构",
    runTime: "运行时间",
    kernelVersion: "内核版本",
    systemStatus: "系统状态",
    memory: "内存",
    disk: "磁盘",
    network: "网络",
  },
  common: {
    choose: "选择"
  },
  global: {
    "changeLog": "更新日志",
    "document": "文档",
    "console": "控制台",
    "plan": "计划",
    "login": "登录",
    "logout": "注销",
  },
  connect: {
    dm:"达梦",
    title: "连接至服务",
    name: "名称",
    group: "分组",
    readOnly: "只读",
    scope: "连接作用范围",
    success: "连接成功!",
    error: "连接出错!",
    global: "全局",
    current: "当前工作空间",
    connecting: "连接",
    save: "保存",
    close: "关闭",
    sshTunnel: "SSH隧道",
    connectTimeout: "连接超时时间",
    requestTimeout: "请求超时",
    useSSL: "SSL",
    hideSystemSchema: "隐藏系统数据库",
    usingConnectString: "使用连接字符串",
    chooseSqlite: "选择数据库文件",
    advance: "高级选项",
  },
  config: {
    safeUpdateMode: "安全更新模式",
    serverType: "服务类型",
    host: "主机名",
    port: "端口",
    username: "用户名",
    password: "密码",
    database: "数据库",
    dialect: "方言",
    driverName: "驱动名",
    driverPath: "驱动路径",
    showedDatabases: "显示的数据库",
    timeZone: "时区",
    groupingTables:"分组表",
    groupingThreshold:"分组阈值",
    trimCountSQL:"清理 Count SQL",
    showForeignKey:"显示外键",
  },
  offline: {
    online: "登录你的premium账号即可, 无机器数量限制.",
    detail: "获取机器码并使用购买premium的邮箱发送到support@database-client.com, 我们将生成激活码并回复, 每个账号最多获取3个离线激活码.",
    getMachineId: "获取机器码",
    activate: "激活",
  },
  result: {
    export: "导出",
    exportOption: "导出选项",
    importExternal: "导入外部数据",
    exportType: "导出类型",
    removeLimit: "移除分页SQL",
    cancel: "取消",
    insert: "保存",
    update: "更新",
    confirm: "确认",
    searchNotice: "输入以搜索数据",
    deleteNotice: "你需要选择至少一条数据!",
    deleteClickHouseNotice: "ClickHouse不支持删除!",
    cost: "耗时",
    copy: "复制",
    editDialog: "编辑行",
    copyDialog: "复制行",
  },
  pay: {
    connectNotice: "<span style='color:var(--vscode-terminal-ansiRed)'>注意</span>: 这个扩展需要付费才能使用全部功能, 如果你反对收费软件, 请立刻卸载, 让我们保持好心情!",
    notice: "这个项目不再免费维护, 现在用户需付费才可使用全部功能. ",
    notice2: "同时我会投入更多的精力开发这个项目, 反馈问题可加Q群: 706495803.",
    freePlanInstalled: "已安装",
    buyPlan: "立刻购买",
  },
  toolbar: {
    reportIssue: "报告问题",
    clearCache: "清除缓存",
    payAdvice: "高级用户将移除这个提示",
  },
  console: {
    configuration: "连接配置",
    resetConfig: "重置",
    edit: "编辑",
    export: "导出",
    import: "导入",
    sync: "云同步",
    mergeConfirm: "存在已创建的连接, 请选择你要执行的操作",
    merge: "合并",
    overwrite: "覆盖",
    upload: "上传",
    download: "下载",
  },
  plan: {
    activation: "激活",
    installed: "已安装",
    perYear: "每年",
    free: "免费",
    about: "关于本项目",
    document: "文档",
    freeTier: "免费试用",
    buyNow: "购买",
    basicNotice: "不会收集你的任何信息以及无广告",
    basicSQLCompletion: "SQL补全",
    basicDesc: "通过简单的方式开始使用Database Client",
    premiumDesc: "对于希望提高生产力的开发工程师",
    allFeature: "所有基础功能",
    otherFeature: "SFTP保存, SQL历史记录支持",
    freeLimitConnection: "限制3个连接",
    unlimitConnection: "无限制的连接",
    cloudSync: "设置云同步",
    workLevelConnection: "工作空间级别的连接",
    intelliSenseSQLCompletion: "更加智能的SQL补全",
  }
}